dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - g++
      - boost1.67

script:
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake .
  - cmake --build . -- -j2
  - ctest -j2 --verbose
